# Generated by Django 5.2.8 on 2025-11-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('business', 'Business Representative'), ('admin', 'Admin')], default='consumer', max_length=20),
        ),
    ]
