# Generated by Django 5.2.8 on 2025-11-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='projection_code',
            field=models.CharField(default='EPSG:3857', help_text="Projection used for map display (e.g., 'EPSG:28416')", max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='projection_definition',
            field=models.TextField(blank=True, help_text='proj4 definition for custom projections (e.g., EPSG:28416)'),
        ),
    ]
