# Generated by Django 5.2.8 on 2025-11-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_city_projection_code_city_projection_definition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
